---
- name: Add nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  sudo: yes

- name: Install nginx
  yum: name=nginx state=present

- name: create certificate folder
  file: path="{{ certificate_dest }}/" state=directory recurse=yes

- name: clone secrets
  local_action: git repo=$secret_url dest=$secret_folder
  sudo: False

- name: create certificate folder
  file: path="{{ certificate_dest }}/" state=directory recurse=yes

# Dont forget to concatenate GandiStandardSSLCA.pem at the end of the certificate
- name: Upload ssl certificate
  copy: 
    src: /home/{{ user }}/.ssh/{{ certificate }}
    dest: "{{ certificate_dest }}/"
  sudo: yes

- name: Set owner for certificate
  shell: chown root:root {{ certificate_dest }}/{{ certificate }}

- name: create certificate key folder
  file: path="{{ certificate_key_dest }}/" state=directory recurse=yes

- name: Upload ssl certificate key
  copy: 
    src: /home/{{ user }}/.ssh/{{ certificate_key }}
    dest: "{{ certificate_key_dest }}/"
  sudo: yes

- name: Set owner for certificate key
  shell: chown root:root {{ certificate_key_dest }}/{{ certificate_key }}

- name: create error pages folder
  file: path="{{ nginx_error_pages }}/" state=directory

- name: copy error pages
  copy: 
    src: 502.html
    dest: $nginx_error_pages
  sudo: yes

- name: Copy nginx configuration
  template: src=codebrew.nginx dest=/etc/nginx/conf.d/codebrew.conf
  notify: restart nginx