sublime_url: http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3047_x64.tar.bz2

fusion_free_url: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-19.noarch.rpm
fusion_nonfree_url: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-19.noarch.rpm