---
- name: Epic team install
  hosts: devs
  user: gui
  roles:
    - jvm
    - user_tools
    - backend_tools
    - frontend_tools
    - elasticsearch
  vars_files:
    - vars/elasticsearch.yml
  vars:
    users:
      - gui
      - jedesah
      - ercomb
      - pat
      - shmed