---
- name: Epic team install
  hosts: devs
  user: gui
  roles:
    - jvm
    - utils
    - backend
    - frontend
  vars:
    users:
      - gui
      - jedesah
      - ercomb
      - pat
      - shmed