---
- name: Epic team install
  hosts: devs
  user: ercomb
  roles:
    # - backend
    - utils
    # - frontend
  vars:
    users:
      - gui
      - jedesah
      - ercomb
      - pat
      - shmed