---
- name: Epic team install
  hosts: devs
  user: gui
  roles:
    - jvm
    - utils
    - backend
    - frontend
    - elasticsearch
  vars_files:
    - common_vars.yml
  vars:
    users:
      - gui
      - jedesah
      - ercomb
      - pat
      - shmed