---
- name: Prod install
  hosts: webapp
  user: $user
  roles:
    # - jvm
    - service_from_sbt
    # - nginx
  vars:
    user: gui
    version_: 0.1.2
    version: v{{ version_ }}
    service_name: codebrew
    service_user: web
    secret_url: git@bitbucket.org:log4900/secret.git
    subproject_name: web