---
- name: Prod install
  hosts: webapp
  user: $user
  roles:
    # - jvm
    - service_from_sbt
    # - nginx
  vars:
    user: gui
    version: HEAD
    service_name: codebrew
    service_user: web
    service_path: 
    service_cmd: 
    subproject_name: server
    subproject_package_task: dist
    subproject_package_directory: server-0.1.0-SNAPSHOT
    subproject_package_archive: "{{ subproject_package_directory }}.zip"
    subproject_package_path: target/universal/{{ subproject_package_archive }}