---
- name: prepare install
  hosts: scala_eval
  user: $user
  roles:
    - jvm
    - service_from_sbt
  vars:
    user: gui
    version_: 0.1.4
    version: v{{ version_ }}
    service_name: scalaEval
    service_user: scalaEval
    secret_url: ""
    subproject_name: scalaEval