---
- name: gather info
  hosts: scala_eval
  gather_facts: True

- name: Prod install
  hosts: webapp
  user: $user
  roles:
    - jvm
    - service_from_sbt
    - nginx
    - firewall
  vars_files:
    - common_vars.yml
  vars:
    user: gui
    version_: 0.1.11
    version: v{{ version_ }}
    service_port: "{{ lookup_port }}"
    service_java_ops:
      - -Dio.codebrew.lookupPort={{ lookup_port }}
    service_users: scala_eval
    service_name: codebrew
    service_user: web
    secret_url: git@bitbucket.org:log4900/secret.git
    subproject_name: web