---
- name: gather info
  hosts: scala_eval

- name: Prod install
  hosts: webapp
  user: $user
  roles:
    - jvm
    - firewall
    - service_from_sbt
    - nginx
  vars:
    user: gui
    version_: 0.1.5
    version: v{{ version_ }}
    service_port: 8000
    service_users: scala_eval
    service_name: codebrew
    service_user: web
    secret_url: git@bitbucket.org:log4900/secret.git
    subproject_name: web