---
- name: gather info
  hosts: webapp
  gather_facts: True

- name: prepare install
  hosts: scala_eval
  user: $user
  roles:
    - firewall
    - jvm
    - service_from_sbt  
  vars_files:
    - vars/lookup.yml
    - vars/codebrew.yml
  vars:
    service_port: 8001
    service_java_ops:
      - -Dio.codebrew.lookupHostname={{ groups['webapp'][0] }}
      - -Dio.codebrew.lookupPort={{ lookup_port }}
      - -Dio.codebrew.scalaEvalHostname={{ ansible_default_ipv4.address }}
      - -Dio.codebrew.scalaEvalPort={{ service_port }}
    service_users: webapp
    service_name: scalaEval
    service_user: scalaEval
    secret_url: ""
    service_subproject_name: scalaEval