---
- name: gather info
  hosts: webapp
  gather_facts: True

- name: prepate deployment
  hosts: local
  connection: local
  gather_facts: false
  user: "{{ user }}"
  roles:
  - prepare_service_from_sbt
  vars_files:
    - vars/eval.yml
    - vars/service.yml
    - vars/codebrew.yml
  vars:
    secret_url: ""

- name: prepare install
  hosts: scala_eval
  user: "{{ user }}"
  roles:
    # - jvm
    - service_from_sbt  
  vars:
    service_ports: [8001, 8002, 8003]
    service_java_ops:
      - -Dio.codebrew.lookupHostname={{ groups['webapp'][0] }}
      - -Dio.codebrew.lookupPort={{ lookup_port }}
      - -Dio.codebrew.scalaEvalHostname={{ ansible_default_ipv4.address }}
    service_users: webapp
    service_name: scalaEval
    service_user: scalaEval
  vars_files:
    - vars/lookup.yml
    - vars/codebrew.yml
    - vars/service.yml
    - vars/eval.yml