---
- name: gather info
  hosts: scala_eval
  gather_facts: True

- name: prepate deployment
  hosts: local
  user: $user
  roles:
  - prepare_service_from_sbt
  vars_files:
    - vars/web.yml
    - vars/service.yml
    - vars/codebrew.yml
  vars:
    secret_url: git@bitbucket.org:log4900/secret.git

- name: Prod install
  hosts: webapp
  user: $user
  roles:
    - firewall
    - jvm
    - elasticsearch
    - service_from_sbt
    - frontend
    - nginx
  vars:
    service_port: "{{ lookup_port }}"
    service_java_ops:
      - -Dio.codebrew.lookupPort={{ lookup_port }}
      - -DapplyEvolutions.default=true
    service_users: scala_eval
    service_name: codebrew
    service_user: web
  vars_files:
    - vars/lookup.yml
    - vars/elasticsearch.yml
    - vars/codebrew.yml
    - vars/frontend.yml
    - vars/web.yml
    - vars/service.yml