---
- name: Epic team user setup
  hosts: devs
  user:
  roles:
    - users
  # vars_prompt:
  #   - name: "pass"
  #     prompt: "Password"
  #     private: yes
  #     encrypt: "sha512_crypt"
  #     confirm: yes
  #     salt_size: 7
  #     salt:
  vars:
    user:
      name:
      pass: $pass