# Make shure sudo visudo has the following line uncommented
#%wheel  ALL=(ALL)       ALL

- name: Create users
  user: name={{ user.name }} groups=wheel shell=/bin/zsh
  sudo: yes

- name: Setup git config
  template: src=.gitconfig.j2 dest=/home/{{ user.name }}/.gitconfig owner={{ user.name }} group={{ user.name }} mode=0664
  sudo: yes

- include: "oh-my-zsh.yml"
