#- name: install haskell platform
#  yum: name="{{ item }}"
#  with_items:
#    - ghc
#    - ghc-prof 
#    - cabal-install
#  sudo: yes

#- name: update cabal
#  command: su -c "cabal update" {{ item }}
#  with_items: "{{ users }}"
#  sudo: yes

- name: update cabal
  command: cabal update
  sudo: yes

- name: install cabal packages globaly
  shell: "env PATH=$PATH:/usr/local/bin; cabal install {{ item }} --global"
  with_items:
    - alex
    - happy
    - aeson
    - base
    - bytestring
    - haskell-src-exts
    - haddock
    - ghc-mod
    - stylish-haskell
    - haskell-docs
    - hdevtools
  sudo: yes
