# # Redhat install (Fedora, CentOS, RedHatLinux, ...)
- name: Register java apps
  command: ls /usr/java/jdk1.7.0_51/bin
  register: java_apps

- name: Install alternatives
  command: >
    update-alternatives --install "/usr/bin/{{ item }}" "{{ item }}" 
    "/usr/java/jdk1.7.0_51/bin/{{ item }}" 1
  with_items: java_apps.stdout_lines
  sudo: yes

- name: Set alternatives
  command: >
    update-alternatives --set "{{ item }}" "/usr/java/jdk1.7.0_51/bin/{{ item }}"
  with_items: java_apps.stdout_lines
  sudo: yes
