- name: add google firewall
  local_action: command gcutil addfirewall codebrew-web --allowed=":https,:http" --project="skillful-skill-363"
  ignore_errors: True

- name: install iptables
  yum: name=iptables
  sudo: yes

- name: Copy iptables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  sudo: yes

- name: Copy ip6tables
  template: src=ip6tables.j2 dest=/etc/sysconfig/ip6tables
  sudo: yes

- name: restart iptables
  service: name=iptables state=restarted
  sudo: yes

- name: restart ip6tables
  service: name=ip6tables state=restarted
  sudo: yes