- name: create download folder
  file: 
    path: /home/Downloads
    state: directory
  sudo: yes

- name: download Sublime Text 3
  get_url: 
    url: $sublime_url
    dest: /home/Downloads/sublime3.tar.bz2

- name: untar Sublime Text 3
  shell: >
    tar -C /opt
    -xjf /home/Downloads/sublime3.tar.bz2
    creates=/opt/sublime_text_3
  sudo: yes

- name: install shortcut
  copy:
    src: sublime_text.desktop
    dest: /usr/share/applications
  sudo: yes

- name: Install typescript plugin
  git: 
    repo: https://github.com/Railk/T3S.git
    dest: /home/{{ item }}/.config/sublime-text-3/Packages/T3S
  with_items: $users

- name: Set owner for typescript plugin
  shell: >
    chown -R {{ item }}:{{ item }}
    /home/{{ item }}/.config/sublime-text-3/Packages/T3S
  with_items: $users

- name: Install typescript plugin synthax
  git: 
    repo: https://github.com/raph-amiard/sublime-typescript.git
    dest: /home/{{ item }}/.config/sublime-text-3/Packages/sublime-typescript
  with_items: $users

- name: Set owner for typescript plugin synthax
  shell: >
    chown -R {{ item }}:{{ item }}
    /home/{{ item }}/.config/sublime-text-3/Packages/sublime-typescript
  with_items: $users