- name: Create ssh folder
  file: 
    state: directory 
    mode: 0700
    dest: /home/{{ user.name }}/.ssh
  sudo: yes

- name: Set owner
  shell: >
    chown {{ user.name }}:{{ user.name }}
    /home/{{ user.name }}/.ssh

- name: Add your public key to authorized keys so you can login with a private key
  copy: src={{ user.name }}/authorized_keys dest=/home/{{ user.name }}/.ssh

- name: Set owner for authorized_keys
  shell: >
    chown {{ user.name }}:{{ user.name }}
    /home/{{ user.name }}/.ssh/authorized_keys