service_project_name: Sauce
service_project_folder: "{{ deployment_folder }}/{{ service_project_name }}"
service_project_git_url: https://github.com/CodeBrew-io/Sauce.git

secret_folder: "{{ deployment_folder }}/secret"

service_dest_root: /opt
service_dest: "{{ service_dest_root }}/{{ subproject_package_directory }}"

subproject_package_directory: "{{ service_subproject_name }}-{{ version_ }}"
subproject_package_archive: "{{ subproject_package_directory }}.zip"
subproject_package_path: "{{ service_subproject_name }}/target/universal/{{ subproject_package_archive }}"